title: Efstathios (Stathis) Daras
description: Software Engineer Portfolio
url: 'https://stathisdaras.github.io'
baseurl: ''

# Theme settings
markdown: kramdown
theme: jekyll-theme-orbit
plugins:
  - jekyll-remote-theme

# Profile information
name: Efstathios (Stathis) Daras
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

# Contact information
email: efstathiosdaras@gmail.com
phone: +30 6974 678 344
#website: blog.webjeda.com #do not add http://
linkedin: stathisdaras
github: stathisdaras
twitter: '@StathisDaras'

# Color scheme
colors:
  primary: "#2ecc71"
  secondary: "#1a252f"
  background: "#121212"
  text: "#ffffff"
  accent: "#2ecc71"

# Google Analytics
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
