title: Efstathios (Stathis) Daras
description: Software Engineer Portfolio
url: 'https://stathisdaras.github.io'
baseurl: ''

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Profile information
name: Efstathios (Stathis) Daras
tagline: Senior Full Stack Engineer
pic: profile.png

# Contact information
email: efstathiosdaras@gmail.com
phone: +41 78 962 04 44

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Color scheme
colors:
  primary: "#0d6efd"
  secondary: "#6c757d"
  background: "#ffffff"
  text: "#212529"
  accent: "#0d6efd"

# Google Analytics
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
